### ISSUE TITLE
Selected buttons not rendering in Mattermost 6.1.0

### ISSUE THREAD

**Issue by NA-Charles** [matterpoll/matterpoll#402] opened 2021-11-23 11:11 UTC
#### Summary
After upgrading the server to 6.1.0 any selected poll options are invisible unless you hover the mouse over them.

#### Steps to reproduce
1. Create a poll
2. Select an option

#### Expected behavior
You should be able to see which options have been selected.

#### Observed behavior (that appears unintentional)
The selected option is now only rendered with a grey border - no text is visible unless you hover the mouse over it.  Note that this is identical in both the web interface and desktop application.

#### Server configuration
Ubuntu 18.04.6 LTS
**Mattermost version: 6.1.0**
**Matterpoll version: 1.4.0**

#### Additional Information
Note that no custom branding or colourization has been applied.

**Comment by hanzei** [comment] 2021-12-02 08:23
Could this be a duplicate of https://github.com/matterpoll/matterpoll/issues/400? Do you see any errors in the webapp console?

**Comment by NA-Charles** [comment] 2021-12-02 12:27
> Could this be a duplicate of #400? Do you see any errors in the webapp console?

It sounds similar, but I don't see any errors in the web console.  Here's an image of what I'm seeing after a vote has been cast.
![image](https://user-images.githubusercontent.com/44259505/144421739-2856413f-432f-4083-816c-74570c4007dd.png)

**Comment by kaakaa** [comment] 2022-01-09 07:54
I can reproduce this and this would be fixed by #374. Since #374 has not been released, please build `master` branch or wait new release.

**Comment by kaakaa** [comment] 2022-06-19 03:04
This issue would be resolved in [v1.5.0](https://github.com/matterpoll/matterpoll/releases/tag/v1.5.0). If the problem still exist, feel free to reopen this issue.

**Closed by kaakaa** 2022-06-19 03:04 UTC
