### ISSUE TITLE
Any Idea about 1.5.0 validation on Mattermost side ?

### ISSUE THREAD

**Issue by nderambure** [matterpoll/matterpoll#448] opened 2022-09-05 15:07 UTC
It's been a long time 1.5.0 is out, and no move from Mattermost.
Any idea why ?

thx !

**Comment by kaakaa** [comment] 2022-09-06 13:50
Thanks for your requests @nderambure .
I’m asking this in [community server](https://community.mattermost.com/core/pl/jj6bfcwbbbgffjj458stdncmyc). 

I think that this is due to the fact that the main person for community plugin is away for a long time. He is also the developer of this project, but I’m sorry I don’t have any more information.

**Comment by nderambure** [comment] 2022-09-06 14:19
Thx you @kaakaa !

**Comment by hanzei** [comment] 2022-09-19 05:51
Closing as duplicate https://github.com/matterpoll/matterpoll/issues/413

**Comment by hanzei** [comment] 2022-09-19 05:51
Duplicate of https://github.com/matterpoll/matterpoll/issues/413

**Closed** 2022-09-19 05:52 UTC
Labels: Question
