### ISSUE TITLE
Multiple choice?

### ISSUE THREAD

**Issue by Domvel** [matterpoll/matterpoll#255] opened 2020-02-07 10:18 UTC
A multiple choice option would be nice. One user should vote for multiple options. Currently an user can only update his vote. The multiple choice vote should toggle the option. If possible highlight the selected option with a background color or another border color or just add something in the text of the option to indicate a vote for the user. e.g. an asterisk. (The feature to highlight current vote can be done in another issue. But it's important especially for multiple choices. If this is not possible for technical reasons, we could find another solution. for example: Improve the poll messages after a vote with markdown stuff or colors if possible.)

Current options:

- `--anonymous`: Don't show who voted for what
- `--progress`: During the poll, show how many votes each answer option got
- `--public-add-option`: Allow all users to add additional options.

New:

- `--multiple-choice`: Allow multiple choice.

(Or just `--multiple` or `--m` ... maybe aliasses.)

**Comment by kaakaa** [comment] 2020-02-11 01:38
Thank you for commenting @Domvel . I start implementing multi answer option according to [this comment](https://github.com/matterpoll/matterpoll/issues/84#issuecomment-543342123).
My implementation will achieve multi choice by `--votes=X` option (`X` is the number of vote that user can give). And if you enable `Experimental UI` setting for Matterpoll, selected option will be highlighted.

But the toggle feature will not be implemented, because the feature to highlight option is now experimental feature, and we don't consider experimental features by default.  Additionally the reason why highlighting is experimental is that we don't have reviewers for webapp.

**Comment by Domvel** [comment] 2020-02-17 13:12
@kaakaa Thanks. I missed this issue #84 on Github search. 
You could use Checkmarks on the left or right of an answer option. If highlight is only available in `Experiemental UI`. But I don't know if the manipulating of the options is possible. Only for the voter and not for all. Or write the current state in the bot message "Your bote has been updated." with the current votes. Just a spontaneous idea.

**Comment by kaakaa** [comment] 2020-02-17 15:05
Thanks @Domvel!

If Checkmarks can be visible only for the voter, it must be handled by client-side (webapp plugin), and it will be also included `Experimental UI` settings. And I suppose that highlighting button is easier to see than checkmarks.

`ExperimentalUI` can be configured from **System Console > Plugins > Matterpoll**, and only system admin may be enable to access `System Console`.  Please try to use Experimental UI.

https://github.com/matterpoll/matterpoll#settings
> You can configure Matterpoll from System Console > Plugins > Matterpoll.
>   * Trigger Word: Change trigger word for poll command. (default /poll)
>   * Experimental UI: Enable new experimental UI for a poll post.

And #256  can display system messages such as "Your vote has been counted. You have 1 vote left.", "You've already voted for this option", and so on.

> For the option votes there should be a value to allow vote all. For example the value 0 or if omitted value. (Nice to have. Otherwise: Just set the value to my options or more. Default is 1 I guess?)

You pointed out good points. Now, with #256 users can specify the positive number between `1` and `the number of options` as `--votes=X`, but it can't handle options added after the poll was created. We'll need to discuss this in #256. Thanks.

**Comment by hanzei** [comment] 2020-03-06 08:57
Closing as duplicate of https://github.com/matterpoll/matterpoll/issues/84

**Closed by hanzei** 2020-03-06 08:57 UTC
Labels: 1. To Develop, Feature Request
